package jri

import (
	fr "github.com/dreyspi/jribot2/frequency"
)

type Preset = []*Food

var BasedPreset = Preset{
	NewFood("пицц", "пицц", fr.Month, 2),
	NewFood("роллс", "роллс", fr.Month, 1),
	NewFood("курица из KFC", "курицу из KFC", fr.Week, 2),
	NewFood("чикан", "чикан", 0, 0),
	NewFood("арбыс или дыня", "арбыс или дыню", fr.Month, 1),
	NewFood("бургерс", "бургерс", fr.Week, 1),
	NewFood("шашлык", "шашлык", fr.Week, 1),
	NewFood("шаурма", "шаурму", fr.Week, 1),
	NewFood("хинкали с хачапури", "хинкали с хачапури", fr.Month, 1),
	NewFood("сэсвич", "сэсвич", fr.Month, 2),
	NewFood("стейк", "стейк", fr.Month, 1),
	NewFood("блин", "блин", fr.Month, 2),
	NewFood("пак гадюки", "пак гадюки", fr.Month, 1),
	NewFood("ночной снэк", "ночной снэк", fr.Week, 2),
	NewFood("рамен", "рамен", fr.Week, 1),
	NewFood("WOK", "WOK", fr.Week, 1),
	NewFood("рыс с яйцом", "рыс с яйцом", fr.Week, 1),
	NewFood("сало", "сало", fr.Month, 2),
	NewFood("CUMнам", "CUMнам", fr.Month, 1),
	NewFood("чабуреки", "чабуреки", fr.Month, 2),
	NewFood("пироженка", "пироженку", fr.Month, 1),
	NewFood("колбаска", "колбаски", fr.Month, 2),
	NewFood("понтовые вафли", "понтовые вафли", fr.Month, 1),
	NewFood("карбонара", "карбонару", fr.Month, 2),
	NewFood("торт", "торт", fr.Month, 1),
}

var ThaiPreset = Preset{
	NewFood("пицц", "пицц", fr.Month, 3),
	NewFood("роллс", "роллс", fr.Month, 1),
	NewFood("курица из KFC", "курицу из KFC", fr.Month, 1),
	NewFood("арбыс или дыня", "арбыс или дыню", fr.Month, 2),
	NewFood("бургерс", "бургерс", fr.Week, 1),
	NewFood("шашлык", "шашлык", fr.Month, 2),
	NewFood("шаурма", "шаурму", fr.Month, 2),
	NewFood("хинкали с хачапури", "хинкали с хачапури", fr.Month, 1),
	NewFood("сэсвич", "сэсвич", fr.Month, 2),
	NewFood("стейк", "стейк", fr.Month, 2),
	NewFood("блин", "блин", fr.Month, 2),
	NewFood("снэк", "снэк", fr.Week, 2),
	NewFood("рамен", "рамен", fr.Week, 1),
	NewFood("тайский рыс", "тайский рыс", fr.Week, 1),
	NewFood("сало", "сало", fr.Month, 2),
	NewFood("корейская куриц", "корейскую куриц", fr.Week, 1),
	NewFood("чабуреки", "чабуреки", fr.Month, 2),
	NewFood("пироженка", "пироженку", fr.Month, 1),
	NewFood("колбаски", "колбаски", fr.Month, 1),
	NewFood("понтовые вафли", "понтовые вафли", fr.Month, 1),
	NewFood("карбонара", "карбонару", fr.Week, 1),
	NewFood("японский рыс", "японский рыс", fr.Week, 1),
	NewFood("индийскую еда", "индийскую еду", fr.Month, 1),
	NewFood("дог", "дог", fr.Month, 1),
	NewFood("рыбс", "рыбс", fr.Month, 1),
	NewFood("такос", "такос", fr.Month, 1),
}

var GeorgianPreset = Preset{
	NewFood("пицц", "пицц", fr.Month, 3),
	NewFood("роллс", "роллс", fr.Month, 1),
	NewFood("курица из KFC", "курицу из KFC", fr.Month, 1),
	NewFood("арбыс или дыня", "арбыс или дыню", fr.Month, 2),
	NewFood("бургерс", "бургерс", fr.Week, 1),
	NewFood("шашлык", "шашлык", fr.Month, 3),
	NewFood("шаурма", "шаурму", fr.Week, 1),
	NewFood("хинкали", "хинкали", fr.Week, 1),
	NewFood("сэсвич", "сэсвич", fr.Month, 2),
	NewFood("стейк", "стейк", fr.Month, 2),
	NewFood("блин", "блин", fr.Month, 2),
	NewFood("снэк", "снэк", fr.Week, 2),
	NewFood("рамен", "рамен", fr.Month, 1),
	NewFood("корейская куриц", "корейскую куриц", fr.Week, 1),
	NewFood("чабуреки", "чабуреки", fr.Month, 2),
	NewFood("пироженка", "пироженку", fr.Month, 1),
	NewFood("понтовые вафли", "понтовые вафли", fr.Month, 1),
	NewFood("карбонара", "карбонару", fr.Week, 1),
	NewFood("японский рыс", "японский рыс", fr.Week, 1),
	NewFood("индийскую еду", "индийскую еду", fr.Month, 1),
	NewFood("китайская", "китайскую", fr.Month, 1),
	NewFood("дог", "дог", fr.Month, 1),
	NewFood("такос", "такос", fr.Month, 1),
	NewFood("хачапури", "хачапури", fr.Month, 1),
	NewFood("оджахури", "оджахури", fr.Month, 2),
	NewFood("киевская котлета", "киевскую котлету", fr.Week, 1),
	NewFood("пельмень", "пельмень", fr.Month, 2),
	NewFood("кебаб", "кебаб", fr.Week, 1),
	NewFood("турецкая еда", "турецкую еду", fr.Month, 1),
	NewFood("греческая еда", "греческую еду", fr.Month, 1),
	NewFood("WOK", "WOK", fr.Month, 2),
	NewFood("плов", "плов", fr.Month, 1),
}
