package jri

import (
	fr "github.com/dreyspi/jribot2/frequency"
)

type Preset = []*Food

var BasedPreset = Preset{
	NewFood("Сожри пицц", fr.Month*2),
	NewFood("Сожри роллс", fr.Month*1),
	NewFood("Сожри курицу из KFC", fr.Week*2),
	NewFood("Сожри чикан", 0),
	NewFood("Сожри арбыс или дыню", fr.Month*1),
	NewFood("Сожри бургерс", fr.Week*1),
	NewFood("Сожри шашлык", fr.Week*1),
	NewFood("Сожри шаурму", fr.Week*1),
	NewFood("Сожри хинкали с хачапури", fr.Month*1),
	NewFood("Сожри сэсвич", fr.Month*2),
	NewFood("Сожри стейк", fr.Month*1),
	NewFood("Сожри блин", fr.Month*2),
	NewFood("Сожри пак гадюки", fr.Month*1),
	NewFood("Сожри ночной снэк", fr.Week*2),
	NewFood("Сожри рамен", fr.Week*1),
	NewFood("Сожри WOK", fr.Week*1),
	NewFood("Сожри рыс с яйцом", fr.Week*1),
	NewFood("Сожри сало", fr.Month*2),
	NewFood("Сожри CUMнам", fr.Month*1),
	NewFood("Сожри чабуреки", fr.Month*2),
	NewFood("Сожри пироженку", fr.Month*1),
	NewFood("Сожри колбаски", fr.Month*2),
	NewFood("Сожри понтовые вафли", fr.Month*1),
	NewFood("Сожри карбонару", fr.Month*2),
	NewFood("Сожри торт", fr.Month*1),
}

var ThaiPreset = Preset{
	NewFood("Сожри пицц", fr.Month*3),
	NewFood("Сожри роллс", fr.Month*1),
	NewFood("Сожри курицу из KFC", fr.Month*1),
	NewFood("Сожри арбыс или дыню", fr.Month*2),
	NewFood("Сожри бургерс", fr.Week*1),
	NewFood("Сожри шашлык", fr.Month*2),
	NewFood("Сожри шаурму", fr.Month*2),
	NewFood("Сожри хинкали с хачапури", fr.Month*1),
	NewFood("Сожри сэсвич", fr.Month*2),
	NewFood("Сожри стейк", fr.Month*2),
	NewFood("Сожри блин", fr.Month*2),
	NewFood("Сожри снэк", fr.Week*2),
	NewFood("Сожри рамен", fr.Week*1),
	NewFood("Сожри тайский рыс", fr.Week*1),
	NewFood("Сожри сало", fr.Month*2),
	NewFood("Сожри корейскую куриц", fr.Week*1),
	NewFood("Сожри чабуреки", fr.Month*2),
	NewFood("Сожри пироженку", fr.Month*1),
	NewFood("Сожри колбаски", fr.Month*1),
	NewFood("Сожри понтовые вафли", fr.Month*1),
	NewFood("Сожри карбонару", fr.Week*1),
	NewFood("Сожри японский рыс", fr.Week*1),
	NewFood("Сожри индийскую еду", fr.Month*1),
	NewFood("Сожри дог", fr.Month*1),
	NewFood("Сожри рыбс", fr.Month*1),
	NewFood("Сожри такос", fr.Month*1),
}

var GeorgianPreset = Preset{
	NewFood("Сожри пицц", fr.Month*3),
	NewFood("Сожри роллс", fr.Month*1),
	NewFood("Сожри курицу из KFC", fr.Month*1),
	NewFood("Сожри арбыс или дыню", fr.Month*2),
	NewFood("Сожри бургерс", fr.Week*1),
	NewFood("Сожри шашлык", fr.Month*3),
	NewFood("Сожри шаурму", fr.Week*1),
	NewFood("Сожри хинкали", fr.Week*1),
	NewFood("Сожри сэсвич", fr.Month*2),
	NewFood("Сожри стейк", fr.Month*2),
	NewFood("Сожри блин", fr.Month*2),
	NewFood("Сожри снэк", fr.Week*2),
	NewFood("Сожри рамен", fr.Month*1),
	NewFood("Сожри корейскую куриц", fr.Week*1),
	NewFood("Сожри чабуреки", fr.Month*2),
	NewFood("Сожри пироженку", fr.Month*1),
	NewFood("Сожри понтовые вафли", fr.Month*1),
	NewFood("Сожри карбонару", fr.Week*1),
	NewFood("Сожри японский рыс", fr.Week*1),
	NewFood("Сожри индийскую еду", fr.Month*1),
	NewFood("Сожри китайскую", fr.Month*1),
	NewFood("Сожри дог", fr.Month*1),
	NewFood("Сожри такос", fr.Month*1),
	NewFood("Сожри хачапури", fr.Month*1),
	NewFood("Сожри оджахури", fr.Month*2),
	NewFood("Сожри киевскую котлету", fr.Week*1),
	NewFood("Сожри пельмень", fr.Month*2),
	NewFood("Сожри кебаб", fr.Week*1),
	NewFood("Сожри турецкую еду", fr.Month*1),
	NewFood("Сожри греческую еду", fr.Month*1),
	NewFood("Сожри WOK", fr.Month*2),
	NewFood("Сожри плов", fr.Month*1),
}
